name: Run Booking Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
            CYPRESS_baseURL: ${{ secrets.BASEURL }}
            CYPRESS_username: ${{ secrets.USERNAME }}
            CYPRESS_password: ${{ secrets.PASSWORD }}
                       
      - name: Upload Cypress report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            cypress/reports/